module.exports={
    UserRoutes:require('./user.routes'),
    AuthRoutes:require('./auth.routes'),
    NeighborhoodRoutes:require('./neighborhood.routes'),
    VehicleRoutes:require('./vehicle.routes'),
    ParkingSpaceRoutes:require('./parkingspace.routes'),
    PositionsRoutes:require('./positions.routes'),
    FileRoutes:require('./file.routes')
}